### ISSUE TITLE
Error on pre-commit hook after cloning

### ISSUE THREAD

**Issue by AdrianRC** [gimyboya/NativeScript-Vue-Typescript-Starter-Kit#1]
**Steps to reproduce**
1. Clone the repo.
2. yarn or npm install.
3. Attempt to commit the updated package-lock or anything else.

**Expected result**
The code is commited.

**Actual result**
The husky pre-commit hook finds an error on `commitlint.config.js`.

```
git commit -m "test"
husky > commit-msg (node v10.15.0)
/Users/adrian/Desktop/hook-test/NativeScript-Vue-Typescript-Starter-Kit/commitlint.config.js:1
(function (exports, require, module, __filename, __dirname) { ��m
                                                              ^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at requireFromString (/Users/adrian/Desktop/hook-test/NativeScript-Vue-Typescript-Starter-Kit/node_modules/require-from-string/index.js:28:4)
    at parseJsFile (/Users/adrian/Desktop/hook-test/NativeScript-Vue-Typescript-Starter-Kit/node_modules/cosmiconfig/dist/loadJs.js:15:15)
husky > commit-msg hook failed (add --no-verify to bypass)
```

**Comment by khawarizmus** [comment]
can you please try to run the command `npm run commit` instead?

**Comment by AdrianRC** [comment]
Just tried it and it doesn't seem to work either.

It seems like the issue is that the `commitlint.config.js` file has `UTF-16 LE` encoding as opposed to `UTF-8` like the rest of the project.
